from QuoteEngine.quotes import QuoteModel
from QuoteEngine.Ingestor import Ingestor 
from QuoteEngine.IngestorInterface import IngestorInterface
from QuoteEngine.JsonIngestor import JsonIngestor
from QuoteEngine.CSVIngestor import CSVIngestor
from QuoteEngine.PDFIngestor import PDFIngestor
from QuoteEngine.DocxIngestor import DocxIngestor
from QuoteEngine.TextIngestor import TextIngestor
from QuoteEngine.MakeQuote import MakeQuote